//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTypes
    {
        public CourseTypes()
        {
            this.Courses = new HashSet<Courses>();
        }
    
        public System.Guid ID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
