//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTopics
    {
        public CourseTopics()
        {
            this.Lectures = new HashSet<Lectures>();
            this.Tests = new HashSet<Tests>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public decimal OrderNumber { get; set; }
        public System.Guid CourseId { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual ICollection<Lectures> Lectures { get; set; }
        public virtual ICollection<Tests> Tests { get; set; }
    }
}
