//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homeworks
    {
        public Homeworks()
        {
            this.HomeworkContent = new HashSet<HomeworkContent>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid StudentId { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public System.Guid LectureId { get; set; }
    
        public virtual ICollection<HomeworkContent> HomeworkContent { get; set; }
        public virtual Students Students { get; set; }
    }
}
