//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureContent
    {
        public System.Guid ID { get; set; }
        public System.Guid LectureId { get; set; }
        public decimal OrderNumber { get; set; }
        public string FileName { get; set; }
    
        public virtual Lectures Lectures { get; set; }
    }
}
