//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectures
    {
        public Lectures()
        {
            this.LectureContent = new HashSet<LectureContent>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid TopicId { get; set; }
        public string Name { get; set; }
        public string Homework { get; set; }
    
        public virtual CourseTopics CourseTopics { get; set; }
        public virtual ICollection<LectureContent> LectureContent { get; set; }
    }
}
