//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELearnerEntities : DbContext
    {
        public ELearnerEntities()
            : base("name=ELearnerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answers> Answers { get; set; }
        public DbSet<CourseCategories> CourseCategories { get; set; }
        public DbSet<CourseRequests> CourseRequests { get; set; }
        public DbSet<Courses> Courses { get; set; }
        public DbSet<CourseTopics> CourseTopics { get; set; }
        public DbSet<CourseTypes> CourseTypes { get; set; }
        public DbSet<GivenAnswers> GivenAnswers { get; set; }
        public DbSet<HomeworkContent> HomeworkContent { get; set; }
        public DbSet<Homeworks> Homeworks { get; set; }
        public DbSet<LectureContent> LectureContent { get; set; }
        public DbSet<Lecturers> Lecturers { get; set; }
        public DbSet<Lectures> Lectures { get; set; }
        public DbSet<QuestionResults> QuestionResults { get; set; }
        public DbSet<Questions> Questions { get; set; }
        public DbSet<StudentCourse> StudentCourse { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TestResults> TestResults { get; set; }
        public DbSet<Tests> Tests { get; set; }
    }
}
