//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Answers = new HashSet<Answers>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid TestId { get; set; }
        public Nullable<decimal> QuestionNumber { get; set; }
        public string QuestionText { get; set; }
    
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
