//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionResults
    {
        public QuestionResults()
        {
            this.GivenAnswers = new HashSet<GivenAnswers>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid TestResultId { get; set; }
        public string QuestionText { get; set; }
        public Nullable<decimal> QuestionNumber { get; set; }
    
        public virtual ICollection<GivenAnswers> GivenAnswers { get; set; }
        public virtual TestResults TestResults { get; set; }
    }
}
