//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public Tests()
        {
            this.Questions = new HashSet<Questions>();
            this.TestResults = new HashSet<TestResults>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.Guid TopicId { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual CourseTopics CourseTopics { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<TestResults> TestResults { get; set; }
    }
}
