//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.GeneratedFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public TestResults()
        {
            this.QuestionResults = new HashSet<QuestionResults>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid StudentId { get; set; }
        public System.Guid TestId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Mark { get; set; }
    
        public virtual ICollection<QuestionResults> QuestionResults { get; set; }
        public virtual Students Students { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
